apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote
        image: ahmedessam404/quotes_app-web:2.0.0
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: postgress

        - name: DB_PORT
          value: "5432"

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
              
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
              
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
